name: PR Branch Labeler

on: pull_request

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
    - name: Label PRs
      #if: github.event.action == 'opened' # Only run the action when the PR was first opened
      uses: rtipirneni/branch-labeler@v1.1
      with:
        repo-token: ${{ secrets.PR_LABELER_TOKEN }}
